{% set name = "theseus-ai" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/theseus-ai-{{ version }}.tar.gz
  sha256: 03a29f774be912a878111ea5301f456dad84b69bc63a3b1706e4e7d841462b90

build:
  number: 8
  skip: true  # [win]
  missing_dso_whitelist:
    # pytorch builds put the libs in the wrong place, but hard to unbundle, see
    # https://github.com/conda-forge/staged-recipes/pull/17082#issuecomment-1189149813
    - '*/libc10{{ SHLIB_EXT }}'
    - '*/libc10_cuda{{ SHLIB_EXT }}'
    - '*/libtorch{{ SHLIB_EXT }}'
    - '*/libtorch_cpu{{ SHLIB_EXT }}'
    - '*/libtorch_cuda{{ SHLIB_EXT }}'
    - '*/libtorch_python{{ SHLIB_EXT }}'
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  # weigh down cpu implementation and give cuda preference
  track_features:
    - theseus-ai-cpu  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
  host:
    - python
    - pytorch
    - pip
    - setuptools
    - cuda-version =={{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')] 
    - libcusparse-dev    # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev    # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - numpy
    - scipy
    - scikit-sparse
    - pybind11
    - torchlie
    - torchkin
    - __cuda >={{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]

test:
  imports:
    - theseus
  requires:
    - pytest

about:
  home: https://github.com/facebookresearch/theseus
  summary: A library for differentiable nonlinear optimization.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
